import { sqliteTable, text, integer, primaryKey, unique } from 'drizzle-orm/sqlite-core'
import { sql } from 'drizzle-orm'
import { users } from './auth.schema'

// Auth tables are generated by better-auth in ./auth.schema.ts.
// Re-exported here so drizzle-kit sees one schema entry point.
export * from './auth.schema'

// --- App tables (DESIGN.md §2) ---

export const project = sqliteTable('project', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  name: text('name').notNull(),
  description: text('description'),
  color: text('color'),
  owner_id: text('owner_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  archived: integer('archived', { mode: 'boolean' }).notNull().default(false),
})

export const task = sqliteTable('task', {
  id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
  title: text('title').notNull(),
  description: text('description'),
  status: text('status', { enum: ['PLANNING', 'IN_PROGRESS', 'COMPLETED', 'DROPPED'] })
    .notNull()
    .default('PLANNING'),
  priority: text('priority', { enum: ['P0', 'P1', 'P2', 'P3', 'P4'] })
    .notNull()
    .default('P2'),
  priority_weight: integer('priority_weight').notNull().default(50),
  project_id: text('project_id').references(() => project.id, { onDelete: 'set null' }),
  created_at: text('created_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  updated_at: text('updated_at').notNull().default(sql`CURRENT_TIMESTAMP`),
  started_at: text('started_at'),
  completed_at: text('completed_at'),
  due_date: text('due_date'),
  owner_id: text('owner_id')
    .notNull()
    .references(() => users.id, { onDelete: 'cascade' }),
  is_trashed: integer('is_trashed', { mode: 'boolean' }).notNull().default(false),
  trashed_at: text('trashed_at'),
})

export const tag = sqliteTable(
  'tag',
  {
    id: text('id').primaryKey().$defaultFn(() => crypto.randomUUID()),
    name: text('name').notNull(),
    owner_id: text('owner_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
  },
  (t) => [unique('tag_owner_name_unique').on(t.owner_id, t.name)],
)

export const task_tags = sqliteTable(
  'task_tags',
  {
    task_id: text('task_id')
      .notNull()
      .references(() => task.id, { onDelete: 'cascade' }),
    tag_id: text('tag_id')
      .notNull()
      .references(() => tag.id, { onDelete: 'cascade' }),
  },
  (t) => [primaryKey({ columns: [t.task_id, t.tag_id] })],
)

export type Project = typeof project.$inferSelect
export type Task = typeof task.$inferSelect
export type Tag = typeof tag.$inferSelect
